---
title: "Lab Meeting Graphs"
author: "Erin"
output: 
html_document:
toc: false
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=F, warning=F, cache=T, message=F, sanitiz =T, fig.width = 5, fig.height = 3)
```

# Load stuff

```{r load_settings}
source("~/Settings/startup.R")
library(reshape2)
theme.new = theme_set(theme_black)
```

```{r load_expt_explanation_data}
expl = read.csv("explanations-expt-data.csv") %>%
  mutate(directional.tag = tag,
         tag = ifelse(tag %in% c("higher", "lower"),
                      "miss", as.character(tag)))
```

```{r load_expt_cf_data}
cf.expt.data = cbind(read.csv("cf-experiment-data.csv") %>%
  mutate(source = factor(source, levels=c("replication human", "lk human"), labels=c("cf.replication", "cf.original"))) %>%
  select(story, variable, source, rating) %>%
  spread(source, rating) %>%
  mutate(story.matcher = ifelse(story%in%c("story3a", "story3b"), "story3", as.character(story))),
  read.csv("cf-experiment-data.csv")$ci.low,
  read.csv("cf-experiment-data.csv")$ci.high) %>%
  rename(replication.low = `read.csv("cf-experiment-data.csv")$ci.low`,
         replication.high = `read.csv("cf-experiment-data.csv")$ci.high`)
cf.model = read.csv("lk-model-data-numbers.csv") %>%
  rename(model = rating) %>%
  mutate(story.matcher = paste("story", story, sep="")) %>%
  select(-story)
cf.model.data = merge(cf.model, cf.expt.data, by=c("story.matcher", "variable"))
all.data = merge(
  (expl %>% mutate(explanation.rating = rating,
                   explanation.high = ci.high,
                   explanation.low = ci.low)),
  cf.model.data,
  by=c("story", "variable", "premise.variable",
       "premise.value", "actual.value")) %>%
  select(-X.x, -X.y, -rating,
         -ci.high, -ci.low, -story.number)
cf.replication.data = read.csv("cf-experiment-data.csv") %>%
  mutate(source = factor(source, levels=c("replication human", "lk human"), labels=c("replication", "original"))) %>%
  select(story, variable, source, rating) %>%
  spread(source, rating)
cf.data = read.csv("cf-experiment-data.csv") %>%
  filter(source == "replication human") %>%
  mutate(story.matcher = ifelse(story %in% c("story3a", "story3b"),
                 "story3", as.character(story))) %>%
  rename(replication = rating)
cf.model.data = merge(cf.data, cf.model, by=c("variable", "story.matcher")) %>% select(-X.x, -X.y, source)
cf.expl = merge(cf.model.data, expl,
                by=c("story", "variable", "premise.variable",
                     "premise.value", "actual.value")) %>%
  rename(explanation.rating = rating,
         explanation.high = ci.high.y,
         explanation.low = ci.low.y,
         cf.rating = replication,
         cf.high = ci.high.x,
         cf.low = ci.low.x,
         cf.model = model) %>%
  mutate(cf.model.of.expl = ifelse(actual.value,
                                   1-cf.model, cf.model),
         empirical.cf.model.of.expl = ifelse(actual.value,
                                             1-cf.rating,
                                             cf.rating),
         cf.model.high = ifelse(actual.value,
                                1-cf.high, cf.high),
         cf.model.low = ifelse(actual.value,
                               1-cf.low, cf.high))
```

# Plot counterfactuals experiment

```{r plot_replication_closeness}
r = round(cor(cf.replication.data$replication, cf.replication.data$original), 2)
cf.replication.data %>%
  ggplot(., aes(original, replication)) +
  geom_point(colour="white") +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cf-replication-closeness.png", width=4, height=3)
```

```{r plot_replication_closeness_stories}
r = round(cor(cf.replication.data$replication, cf.replication.data$original), 2)
cf.replication.data %>%
  ggplot(., aes(original, replication, colour=story,
                shape=variable)) +
  geom_point(size=4) +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  theme_black +
  scale_colour_brewer(type="qual", palette = 2)
  ggsave("lab-meeting-graphs/cf-replication-closeness-stories.png", width=7, height=4.25)
```

```{r plot_orig_cf_model_data}
r = round(cor(all.data$model, all.data$cf.original), 2)
all.data %>%
  ggplot(., aes(model, cf.original)) +
  geom_point(colour="white") +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  # geom_errorbarh(aes(xmin=ci.low, xmax=ci.high), height=0, colour="white") +
  theme_black +
  xlab("model") +
  ylab("original data") +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfdata-original.png", width=4, height=3)
```

```{r plot_orig_cf_model_data_stories}
r = round(cor(all.data$model, all.data$cf.original), 2)
all.data %>%
  ggplot(., aes(model, cf.original, colour=story,
                shape=variable)) + 
  geom_point(size=4) +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  # geom_errorbarh(aes(xmin=ci.low, xmax=ci.high), height=0, colour="white") +
  theme_black +
  xlab("model") +
  ylab("original data") +
  scale_colour_brewer(type="qual", palette = 2)
  ggsave("lab-meeting-graphs/cfdata-original-stories.png", width=7, height=4.25)
```

```{r plot_cf_model_data}
r = round(cor(all.data$model, all.data$cf.replication), 2)
all.data %>%
  ggplot(., aes(model, cf.replication)) +
  geom_point(colour="white") +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  # geom_errorbarh(aes(xmin=ci.low, xmax=ci.high), height=0, colour="white") +
  theme_black +
  ylab("replication data") +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfdata-replication.png", width=4, height=3)
```

```{r plot_cf_model_data_stories}
r = round(cor(all.data$model, all.data$cf.replication), 2)
all.data %>%
  ggplot(., aes(model, cf.replication, colour=story, shape=variable)) +
  geom_point(size=4) +
  # annotate(geom="text", label=paste("r=", r, sep=""), colour="white", y=0.9, x=0.1) +
  # geom_errorbarh(aes(xmin=ci.low, xmax=ci.high), height=0, colour="white") +
  theme_black +
  ylab("replication data") +
  theme(legend.position="right") +
  scale_colour_brewer(type="qual", palette = 2)
  ggsave("lab-meeting-graphs/cfdata-replication-stories.png", width=7, height=4.25)
```

# Plot CF prob vs Explanations

```{r plot_cf_prob}
r = round(cor(cf.expl$cf.model.of.expl, cf.expl$explanation.rating), 2)
cf.expl %>%
  ggplot(., aes(x=cf.model.of.expl, y=explanation.rating)) +
  geom_point(colour="white") +
  # annotate(geom="text", label=paste("r=", r, sep=""),
           # colour="white", x=0.1, y=0.9) +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0, colour="white") +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(0,1.001) +
  xlim(0,1.001) +
  ylab("explanation rating") +
  xlab("model CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob.png", width=4, height=3)
```

```{r plot_cf_prob_stories}
r = round(cor(cf.expl$cf.model.of.expl, cf.expl$explanation.rating), 2)
cf.expl %>%
  ggplot(., aes(x=cf.model.of.expl, y=explanation.rating,
                colour=story, shape=variable)) +
  geom_point(size=4) +
  # annotate(geom="text", label=paste("r=", r, sep=""),
           # colour="white", x=0.1, y=0.9) +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0) +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(0,1.001) +
  xlim(0,1.001) +
  ylab("explanation rating") +
  xlab("model CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob-stories.png", width=7.5, height=4.25)
```

```{r plot_cf_prob_tagged}
cf.expl %>%
  ggplot(., aes(x=cf.model.of.expl, y=explanation.rating, colour=tag)) +
  geom_point() +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0) +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(-0.001,1.001) +
  xlim(-0.001,1.001) +
  ylab("explanation rating") +
  xlab("CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob-tagged.png", width=5, height=3)
```

```{r plot_empirical_cf_prob}
r = round(cor(cf.expl$empirical.cf.model.of.expl, cf.expl$explanation.rating), 2)
cf.expl %>%
  ggplot(., aes(x=empirical.cf.model.of.expl, y=explanation.rating)) +
  geom_point(colour="white") +
  # annotate(geom="text", label=paste("r=", r, sep=""),
  #          colour="white", x=0.1, y=0.9) +
  geom_errorbarh(aes(y=explanation.rating,
                     xmin=cf.model.low, xmax=cf.model.high), height=0, colour="white") +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0, colour="white") +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(0,1) +
  xlim(0,1) +
  ylab("explanation rating") +
  xlab("empirical CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob-empirical.png", width=4, height=3)
```
  
```{r plot_empirical_cf_prob_story}
r = round(cor(cf.expl$empirical.cf.model.of.expl, cf.expl$explanation.rating), 2)
cf.expl %>%
  ggplot(., aes(x=empirical.cf.model.of.expl, y=explanation.rating,
                colour=story, shape=variable)) +
  geom_point(size=4) +
  # annotate(geom="text", label=paste("r=", r, sep=""),
  #          colour="white", x=0.1, y=0.9) +
  geom_errorbarh(aes(y=explanation.rating,
                     xmin=cf.model.low, xmax=cf.model.high), height=0) +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0) +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(0,1) +
  xlim(0,1) +
  ylab("explanation rating") +
  xlab("empirical CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob-empirical-stories.png", width=7, height=4.25)
```
  
```{r plot_empirical_cf_prob_tagged}
cf.expl %>%
  ggplot(., aes(x=empirical.cf.model.of.expl, y=explanation.rating, colour=tag)) +
  geom_point() +
  geom_errorbarh(aes(y=explanation.rating,
                     xmin=cf.model.low, xmax=cf.model.high), height=0) +
  geom_errorbar(aes(ymin=explanation.low, ymax=explanation.high), width=0) +
  scale_colour_brewer(type="qual", palette = 2) +
  ylim(0,1) +
  xlim(0,1) +
  ylab("explanation rating") +
  xlab("empirical CF prob") + theme_black +
  theme(legend.position="right")
  ggsave("lab-meeting-graphs/cfprob-empirical-tagged.png", width=5, height=3)
```

# Plot RSA base explanations model

```{r define_explanations_rating_function}
get_model_var = function(utterance, explanandum, speaker, cost) {
  if (speaker == "weird_s2") {
    return(paste("s2('", utterance, "', ", cost, ", '", explanandum, "', 'varies')", sep=""))
  } else if (speaker == "s2") {
    return(paste("s2('", utterance, "', ", cost, ", '", explanandum, "', 'all_alternatives')", sep=""))
  } else if (speaker == "speaker") {
    return(paste("function() {return sample(speakerERP(':", utterance, "', ", cost, "));}", sep=""))
  } else if (speaker == "literal") {
    return(paste("function() {return sample(literalERP('", utterance, "'));}", sep=""))
  }
}
get_program_file = function(story.number, variable, 
                            causal.uncertainty) {
  if (causal.uncertainty=="base") {
    return(paste("rsa.base.booleans/lk",
                 story.number,
                 "/autoexpanded.wppl", sep=""))
  } else if (causal.uncertainty=="fulllink") {
    return(paste("rsa.base.booleans/lk",
                 story.number,
                 "/autoexpanded.wppl", sep=""))
  } else if (causal.uncertainty=="onelink") {
    return(paste("rsa.onelink.booleans/lk",
                 story.number,
                 variable,
                 "/autoexpanded.wppl", sep=""))
  }
}
rate.expl = function(story.number, variable, actual.value,
                     premise.variable, premise.value, 
                     causal.uncertainty, speaker, cost) {
  explanandum = paste(ifelse(actual.value, "", "! "), variable, sep="")
  explanans = paste(ifelse(premise.value, "! ", ""), premise.variable, sep="")
  utterance = paste(explanandum, " because ", explanans, sep="")
  
  model_var = get_model_var(utterance, explanandum, speaker, cost)
  program_file = get_program_file(story.number, variable, causal.uncertainty)

  rs = webppl(
    program_file = program_file,
    model_var = model_var,
    inference_opts = list(method="enumerate"),
    packages = "./node_modules/jsUtils")
  if (speaker=="literal") {
    return(rs)
  }
  prob_utterance = rs$prob[rs$support==utterance]

  return(prob_utterance)
}
plot.expl = function(df, filename) {
  df %>%
    ggplot(., aes(x=model, y=rating)) +
    geom_point(colour="white") +
    geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0, colour="white") +
    scale_colour_brewer(type="qual", palette = 2) +
    ylim(0, 1) +
    xlim(0, 1)
  ggsave(paste("lab-meeting-graphs/", filename, sep=""), width=4, height=3)
}
plot.expl.with.stories = function(df, filename) {
  df %>%
    ggplot(., aes(x=model, y=rating, colour=story,
                  shape=variable)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0) +
    scale_colour_brewer(type="qual", palette = 2) +
    ylim(0, 1) +
    xlim(0, 1)
  ggsave(paste("lab-meeting-graphs/", filename, sep=""), width=7, height=4.25)
}
```

```{r run_rsa_base_weird_s2_model}
rsa_base_weird_s2 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "weird_s2"))
```

```{r plot_rsa_base_weird_s2_model}
plot.expl(rsa_base_weird_s2, "rsa-base-weird-s2.png")
```

```{r plot_rsa_base_weird_s2_model_stories}
plot.expl.with.stories(rsa_base_weird_s2, "rsa-base-weird-s2-stories.png")
```

```{r plot_rsa_base_weird_s2_model_stories}
rsa_base_weird_s2 %>%
    ggplot(., aes(x=model, y=rating, colour=tag)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0) +
    scale_colour_brewer(type="qual", palette = 2) +
    ylim(0, 1) +
    xlim(0, 1)
  ggsave("lab-meeting-graphs/rsa-base-weird-s2-tagged.png", width=7, height=4.25)
```

```{r run_rsa_base_s2_model}
rsa_base_s2 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "s2", 0))
```

```{r plot_rsa_base_s2_model}
plot.expl(rsa_base_s2, "rsa-base-s2.png")
```

```{r plot_rsa_base_s2_model_filtered}
rsa_base_s2 %>%
  filter(char(premise.variable) != char(variable)) %>%
  plot.expl(., "rsa-base-s2-filtered.png")
```

```{r plot_rsa_base_s2_model_filtered_stories}
rsa_base_s2 %>%
  filter(char(premise.variable) != char(variable)) %>%
  plot.expl.with.stories(., "rsa-base-s2-filtered-stories.png")
```

```{r plot_rsa_base_s2_model_tagged}
rsa_base_s2 %>%
    ggplot(., aes(x=model, y=rating, colour=tag)) +
    geom_point(size=4) +
    geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0) +
    scale_colour_brewer(type="qual", palette = 2) +
    ylim(0, 1) +
    xlim(0, 1)
  ggsave("lab-meeting-graphs/rsa-base-s2-tagged.png", width=7, height=4.25)
```

```{r plot_rsa_base_s2_model_stories}
plot.expl.with.stories(rsa_base_s2, "rsa-base-s2-stories.png")
```

```{r run_rsa_base_s1_model}
rsa_base_s1 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "speaker", 0))
```

```{r plot_rsa_base_s1_model}
plot.expl(rsa_base_s1, "rsa-base-s1.png")
```

```{r plot_rsa_base_s1_model_stories}
plot.expl.with.stories(rsa_base_s1, "rsa-base-s1-stories.png")
```

```{r run_rsa_base_s2_cost1_model}
rsa_base_s2_cost1 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "s2", 1))
```

```{r plot_rsa_base_s2_cost1_model}
plot.expl(rsa_base_s2_cost1, "rsa-base-s2-cost1.png")
```

```{r plot_rsa_base_s2_model_cost1_stories}
plot.expl.with.stories(rsa_base_s2_cost1, "rsa-base-s2-cost1-stories.png")
```

```{r run_rsa_base_s2_cost5_model}
rsa_base_s2_cost5 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "s2", 5))
```

```{r plot_rsa_base_s2_cost5_model}
plot.expl(rsa_base_s2_cost5, "rsa-base-s2-cost5.png")
```

```{r plot_rsa_base_s2_model_cost5_stories}
plot.expl.with.stories(rsa_base_s2_cost5, "rsa-base-s2-cost5-stories.png")
```

```{r run_rsa_base_s2_cost10_model}
rsa_base_s2_cost10 = expl %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "base", "s2", 10))
```

```{r plot_rsa_base_s2_cost10_model}
plot.expl(rsa_base_s2_cost10, "rsa-base-s2-cost10.png")
```

```{r plot_rsa_base_s2_model_cost10_stories}
plot.expl.with.stories(rsa_base_s2_cost10, "rsa-base-s2-cost10-stories.png")
```

# Explain RSA base explanations model

```{r define_literal_fn}
literal = function(story.number, variable, causal.uncertainty, utterance) {
  rs = webppl(
    program_file = get_program_file(
      story.number, variable, causal.uncertainty),
    model_var = paste("function() {return sample(literalERP('", utterance, "'));}", sep=""),
    inference_opts = list(method="enumerate"),
    packages = "./node_modules/jsUtils"
  )
  rs$utterance = utterance
  rs$causal.uncertainty = causal.uncertainty
  return(rs)
}
print_world = function(a, b, c, d, cause) {
  paste(
    ifelse(a, "A", ""),
    ifelse(b, "B", ""),
    ifelse(c, "C", ""),
    ifelse(d, "D", ""),
    ifelse(cause, "cause", "")
  )
}
```

```{r rsa_base_literal_story1b}
story1b = rbind(literal(1, "B", "base", "B because A"),
      literal(1, "B", "base", "")) %>%
  mutate(world = mapply(print_world, output.A, output.B, F, F, F))
# story1b %>% ggplot(., aes(x=world, y=prob, fill=utterance)) +
#     geom_bar(stat="identity", position="dodge") +
#     scale_fill_brewer(type="qual", palette = 2)
story1b %>% rename(B=output.B, A=output.A) %>%
  gather("variable", "value", c(A, B)) %>%
  group_by(utterance, variable) %>%
  summarise(marginal.prob = sum(prob[value])) %>%
  ggplot(., aes(x=utterance, y=marginal.prob)) +
  geom_bar(stat="identity", position="dodge") +
  scale_colour_brewer(type="qual", palette = 2) +
  facet_wrap(~variable, scale="free") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
ggsave("lab-meeting-graphs/rsa_base_literal.png", width=5, height=5)
```

```{r rsa_base_literal_story2a}
story2a = rbind(literal(2, "A", "base", "A because B"),
      literal(2, "A", "base", "")) %>%
  mutate(world = mapply(print_world, output.A, output.B, output.C, F))
# story2a %>% ggplot(., aes(x=world, y=prob, fill=utterance)) +
#     geom_bar(stat="identity", position="dodge") +
#     scale_fill_brewer(type="qual", palette = 2)
story2a %>% rename(B=output.B, A=output.A, C=output.C) %>%
  gather("variable", "value", c(A, B, C)) %>%
  group_by(utterance, variable) %>%
  summarise(marginal.prob = sum(prob[value])) %>%
  ggplot(., aes(x=utterance, y=marginal.prob)) +
  geom_bar(stat="identity", position="dodge") +
  scale_colour_brewer(type="qual", palette = 2) +
  facet_wrap(~variable, scale="free") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
ggsave("lab-meeting-graphs/rsa_base_literal_story2a.png", width=7, height=5)
```

```{r rsa_base_literal_story3c}
story3c = rbind(literal(3, "C", "base", "! C because A"),
      literal(3, "C", "base", "")) %>%
  mutate(world = mapply(print_world, output.A, output.B, output.C, F))
# story3c %>% ggplot(., aes(x=world, y=prob, fill=utterance)) +
#     geom_bar(stat="identity", position="dodge") +
#     scale_fill_brewer(type="qual", palette = 2)
story3c %>% rename(B=output.B, A=output.A, C=output.C) %>%
  gather("variable", "value", c(A, B, C)) %>%
  group_by(utterance, variable) %>%
  summarise(marginal.prob = sum(prob[value])) %>%
  ggplot(., aes(x=utterance, y=marginal.prob)) +
  geom_bar(stat="identity", position="dodge") +
  scale_colour_brewer(type="qual", palette = 2) +
  facet_wrap(~variable, scale="free") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
ggsave("lab-meeting-graphs/rsa_base_literal_story3c.png", width=7, height=5)
```

# Plot RSA onelink

```{r run_rsa_onelink_s2_model}
rsa_onelink_s2 = expl %>%
  # filter(char(variable) != char(premise.variable)) %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "onelink", "s2", 0))
```

```{r plot_rsa_onelink_s2_model}
plot.expl(rsa_onelink_s2, "rsa-onelink-s2.png")
```

```{r plot_rsa_onelink_s2_model_filtered_stories}
plot.expl.with.stories(
  rsa_onelink_s2 %>%
    filter(char(variable) != char(premise.variable)),
  "rsa-onelink-s2-filteredstories.png")
```

```{r plot_rsa_onelink_s2_model_stories}
plot.expl.with.stories(rsa_onelink_s2, "rsa-onelink-s2-stories.png")
```

```{r run_rsa_onelink_s2_cost10_model}
rsa_onelink_s2_cost10 = expl %>%
  # filter(char(variable) != char(premise.variable)) %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "onelink", "s2", 10))
```

```{r plot_rsa_onelink_s2_cost10_model}
plot.expl(rsa_onelink_s2_cost10, "rsa-onelink-s2-cost10.png")
```

```{r plot_rsa_onelink_s2_cost10_model_filtered_stories}
plot.expl.with.stories(
  rsa_onelink_s2_cost10 %>%
    filter(char(variable) != char(premise.variable)),
  "rsa-onelink-s2-cost10-filteredstories.png")
```

```{r plot_rsa_onelink_s2_cost10_model_stories}
plot.expl.with.stories(rsa_onelink_s2_cost10, "rsa-onelink-s2-cost10-stories.png")
```

# Testing / Debugging

```{r run_rsa_onelink_s2_model}
rsa_onelink_s2 = expl %>%
  filter(story=="story5" & variable=="D") %>%
  mutate(model = mapply(rate.expl, story.number, variable,
                        actual.value, premise.variable, 
                        premise.value, "onelink", "s2", 0))
rsa_onelink_s2
```

```{r testing_higherOrderForwardSample}
rs = webppl(
    program_file = "rsa.onelink.booleans/lk4D/autoexpanded.wppl",
    model_var = paste("function() {return evenHigherOrderForwardSample();}", sep=""),
    inference_opts = list(method="enumerate"),
    packages = "./node_modules/jsUtils"
  ) %>%
  mutate(world = mapply(print_world, output.A, output.B,
                        output.C, output.D, structureParams.cause))
rs %>%
  ggplot(., aes(x=world, y=prob)) +
  geom_bar(stat="identity") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
```

```{r story4d_onelink}
story4d = rbind(literal(4, "D", "onelink", "D because C"),
      literal(4, "D", "onelink", "")) %>%
  mutate(world = mapply(print_world, output.A, output.B, output.C, output.D, structureParams.cause))

story4d %>% ggplot(., aes(x=world, y=prob, fill=utterance)) +
  geom_bar(stat="identity", position="dodge") +
  scale_fill_brewer(type="qual", palette = 2) +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))

story4d %>%
  rename(B=output.B, A=output.A, C=output.C, D=output.D,
         cause = structureParams.cause) %>%
  gather("variable", "value", c(A, B, C, D, cause)) %>%
  group_by(utterance, variable) %>%
  summarise(marginal.prob = sum(prob[value])) %>%
  ggplot(., aes(x=utterance, y=marginal.prob)) +
  geom_bar(stat="identity", position="dodge") +
  scale_colour_brewer(type="qual", palette = 2) +
  facet_wrap(~variable, scale="free") +
  theme(axis.text.x = element_text(angle = -90, hjust = 0))
ggsave("lab-meeting-graphs/rsa_onelink_literal_story4d.png", width=5, height=5)
```

```{r}
literal = function(story.number, variable, causal.uncertainty, utterance) {
  rs = webppl(
    program_file = get_program_file(
      story.number, variable, causal.uncertainty),
    model_var = paste("function() {return sample(literalERP('", utterance, "'));}", sep=""),
    inference_opts = list(method="enumerate"),
    packages = "./node_modules/jsUtils"
  )
  rs$utterance = utterance
  rs$causal.uncertainty = causal.uncertainty
  return(rs)
}
print_world = function(a, b) {
  paste(
    ifelse(a, "A", ""),
    ifelse(b, "B", "")
  )
}
story1b = rbind(
  literal(1, "B", "onelink", ""),
literal(1, "B", "onelink", "B because A"))  %>%
  mutate(world = mapply(print_world, output.A, output.B))
story1b %>%
  rename(cause = structureParams.cause) %>%
  group_by(cause, utterance) %>%
  summarise(marginal.prob = sum(prob)) %>%
  ggplot(., aes(x=cause, y=marginal.prob,
                fill=utterance)) +
  geom_bar(stat="identity", position="dodge")
story1b %>%
  ggplot(., aes(x=world, y=prob,
                fill=utterance)) +
  geom_bar(stat="identity", position="dodge") +
  theme(axis.text.x = element_text(angle = -45, hjust = 0)) +
  scale_fill_brewer(type='qual', palette = 2)
ggsave("lab-meeting-graphs/story1b-full.png", width=7, height=4.25)
```

```{r}
print_world = function(cause, a, b, ab) {
  paste(
    ifelse(cause, "cause", ""),
    ifelse(a, "A", ""),
    ifelse(b, "B", ""),
    ifelse(ab, "ab", "")
  )
}
story1b = rbind(
  rate.expl(1, "B", T, "A", F, "onelink", "literal", 0) %>%
    mutate(causal.uncertainty=T,
           world = mapply(print_world, structureParams.cause, output.A, output.B, input.ab)) %>%
    select(world, prob, causal.uncertainty),
  rate.expl(1, "B", T, "A", F, "base", "literal", 0) %>% mutate(causal.uncertainty=F,
           world = mapply(print_world, F, output.A, output.B, F)) %>%
    select(world, prob, causal.uncertainty))
story1b
```

```{r story1_base_vs_onelink}
compare_base_vs_onelink = function(storynum, this.var,
                                   actual.value, premise.variable,
                                   premise.value) {
  data.frame(
    causal.uncertainty = c(T, F),
    model = c(rate.expl(storynum, this.var, actual.value, premise.variable, premise.value, "onelink", "speaker", 0),
              rate.expl(storynum, this.var, actual.value, premise.variable, premise.value, "base", "speaker", 0))
  ) %>%
    ggplot(., aes(x=causal.uncertainty, y=model)) +
    geom_hline(yintercept = (expl %>% filter(story==paste("story", storynum, sep="") & variable==this.var))$rating, colour="white") +
    geom_hline(yintercept = (expl %>% filter(story==paste("story", storynum, sep="") & variable==this.var))$ci.high, colour="darkgray") +
    geom_hline(yintercept = (expl %>% filter(story==paste("story", storynum, sep="") & variable==this.var))$ci.low, colour="darkgray") +
    geom_bar(stat="identity") +
    ylim(0, 1)
  ggsave(paste("lab-meeting-graphs/story", storynum, this.var, "-causal-uncertainty-comparison.png", sep=""), width=3, height=3)
}
compare_base_vs_onelink(1, "B", T, "A", F)
compare_base_vs_onelink(2, "A", T, "B", F)
compare_base_vs_onelink(2, "C", T, "B", F)
```

```{r lk1_rsa}
rs = webppl(
  # program_file = "rsa.base.booleans/lk1/autoexpanded.wppl",
  program_file = "rsa.onelink.booleans/lk1B/autoexpanded.wppl",
  inference_opts = list(method="enumerate"),
  # model_var = "function() {return sample(literalERP(''));}",
  model_var = "function() {return sample(literalERP('B because A'));}",
  # model_var = "function() {return sample(speakerERP(':B because A', 0));}",
  # model_var = "s2('B because A', 0, 'B', 'all_alternatives')",
  packages = "./node_modules/jsUtils"
)
rs %>% filter(structureParams.cause==F &
  output.A & output.B)

rate.expl(1, "B", T, "A", F, "onelink", "speaker", 0)
rate.expl(1, "B", T, "A", F, "base", "speaker", 0)

rate.expl(2, "A", T, "B", F, "onelink", "speaker", 0)
rate.expl(2, "A", T, "B", F, "base", "speaker", 0)
```
