---
title: "All booleans! Vary structure!"
author: "Erin Bennett"
output: 
html_document:
toc: false
bibliography: "../../explanations.bib"
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=F, warning=F, cache=T, message=F, sanitiz =T, fig.width = 5, fig.height = 3)
```

```{r load_settings}
# install.packages('devtools')
# devtools::install_github("mhtess/rwebppl")
source("~/Settings/startup.R")
library(reshape2)
```

## 1. Using only boolean variables, do counterfactual probabilities match up with L&K's model?

Yep.

```{r}
counterfactual = function(model, variable, storynumber,
                          premise.variable, premise.value) {
  program_file = paste(model, "/lk", storynumber,
                       "/autoexpanded.wppl", sep="")
  rs = webppl(program_file = program_file,
              inference_opts = list(method="enumerate"),
              model_var = paste(
                "function() {return counterfactual(0.53, {'",
                premise.variable,
                "': ",
                ifelse(premise.value, "true", "false"),
                "});}",
                sep=""),
              packages = "./node_modules/jsUtils")
  return(sum(rs[rs[[variable]]==T, "prob"]))
}
```

```{r}
lk.model = read.csv("lk-model-data-numbers.csv") %>%
  mutate(my.model = mapply(counterfactual, "rsa.base.booleans", variable,
                           story, premise.variable, premise.value),
         story = factor(story))

# lk.model %>% ggplot(., aes(x=rating, y=my.model, colour=story)) +
#   geom_point()
```

## 2. What about explanations?

<!--

```{r}
explanation = function(model, variable, storynumber,
                       premise.variable, premise.value,
                       actual.value) {
  premise = paste(ifelse(premise.value, "", "! "), premise.variable, sep="")
  explanans = paste(ifelse(premise.value, "! ", ""), premise.variable, sep="")
  explanandum = paste(ifelse(actual.value, "", "! "), variable, sep="")
  expl = paste(explanandum, " because ", explanans, sep="")
  rs = webppl(program_file = paste(model, "/lk", storynumber,
                                   "/autoexpanded.wppl", sep=""),
              inference_opts = list(method="enumerate"),
              model_var = "speaker",
              packages = "./node_modules/jsUtils")
  return(
    (rs %>% filter(support==expl))$prob
  )
}
```

```{r}
lk.model.with.expl = read.csv("lk-model-data-numbers.csv") %>%
  mutate(model.expl.rating = mapply(explanation, "rsa.base.booleans", variable,
                           story, premise.variable, premise.value, actual.value),
         story = factor(story))
```

```{r}
lk.model.with.expl %>% ggplot(., aes(x=model.expl.rating)) +
  geom_point()
```

```{r}
expl = read.csv("explanations-expt-data.csv")
expl %>% mutate(model = rsa.base) %>%
  ggplot(aes(x=model, y=rating)) +
  # geom_abline(intercept = 0, slope=1, colour="gray") +
  geom_point(colour="white") +
  geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0, colour="white") +
  ylim(0, 1) +
  xlab("model") +
  ylab("data") +
  ggtitle("RSA.BASE")
ggsave("rsa.base.png", width=4, height=3)
```

## 3. What happens when we introduce structural uncertainty for *one* link?

```{r}
rsA = webppl(program_file = "rsa.onelink.booleans/lk1-A/autoexpanded.wppl",
             inference_opts = list(method="enumerate"),
             model_var = "speaker",
             packages = "./node_modules/jsUtils") %>%
  mutate(prob = prob)
# rsB = webppl(program_file = "rsa.onelink.booleans/lk1-B/autoexpanded.wppl",
#              inference_opts = list(method="enumerate"),
#              model_var = "speaker",
#              packages = "./node_modules/jsUtils") %>%
#   mutate(prob = prob)
# rsa.BmightCauseA = c((rsA %>% filter(support=="A because A"))$prob,
#                      (rsA %>% filter(support=="B because A"))$prob)
rsa.AmightCauseB = c((rsA %>% filter(support=="A because A"))$prob,
                     (rsA %>% filter(support=="B because A"))$prob)
# rsa.mix = c((rsA %>% filter(support=="A because A"))$prob,
#             b.bc.a = (rsA %>% filter(support=="B because A"))$prob)
```

```{r}
expl = read.csv("explanations-expt-data.csv")
expl %>% mutate(model = rsa.AmightCauseB) %>%
  ggplot(aes(x=model, y=rating)) +
  # geom_abline(intercept = 0, slope=1, colour="gray") +
  geom_point(colour="white") +
  geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0, colour="white") +
  ylim(0, 1) +
  xlab("model") +
  ylab("data") +
  ggtitle("rsa.AmightCauseB")
ggsave("rsa.AmightCauseB.png", width=4, height=3)
```

```{r}
expl = read.csv("explanations-expt-data.csv")
expl %>% mutate(model = rsa.mix) %>%
  ggplot(aes(x=model, y=rating)) +
  # geom_abline(intercept = 0, slope=1, colour="gray") +
  geom_point(colour="white") +
  geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0, colour="white") +
  ylim(0, 1) +
  xlab("model") +
  ylab("data") +
  ggtitle("rsa.mix")
ggsave("rsa.mix.png", width=4, height=3)
```

```{r}
expl = read.csv("explanations-expt-data.csv")
expl %>% mutate(model = rsa.AmightCauseB) %>%
  ggplot(aes(x=model, y=rating)) +
  # geom_abline(intercept = 0, slope=1, colour="gray") +
  geom_point(colour="white") +
  geom_errorbar(aes(ymin=ci.low, ymax=ci.high), width=0, colour="white") +
  ylim(0, 1) +
  xlab("model") +
  ylab("data") +
  ggtitle("rsa.AmightCauseB")
ggsave("rsa.AmightCauseB.png", width=4, height=3)
```


```{r}
counterfactual.by.variable = function(model, variable, storynumber,
premise.variable, premise.value) {
program_file = paste(model, "/lk", storynumber, "-", variable,
"/autoexpanded.wppl", sep="")
rs = webppl(program_file = program_file,
inference_opts = list(method="enumerate"),
model_var = paste(
"function() {return counterfactual(0.53, {'",
premise.variable,
"': ",
ifelse(premise.value, "true", "false"),
"});}",
sep=""),
packages = "./node_modules/jsUtils")
return(sum(rs[rs[[variable]]==T, "prob"]))
}
```

```{r}
rs = webppl(program_file = "rsa.onelink.booleans/lk1-A/autoexpanded.wppl",
inference_opts = list(method="enumerate"),
model_var = paste(
#"forwardSample",
#"highOrderForwardSample",
"function() {return counterfactual(0.53, {A: false});}",
sep=""),
packages = "./node_modules/jsUtils")
rs
```

```{r}
lk.model = read.csv("lk-model-data-numbers.csv") %>%
filter(story%in%1:4) %>%
mutate(my.model = mapply(counterfactual.by.variable,
"rsa.onelink.booleans", variable,
story, premise.variable, premise.value),
story = factor(story))

lk.model %>% ggplot(., aes(x=rating, y=my.model, colour=story)) +
geom_point()
```
-->

## 4. How do explanations compare with and without uncertainty about one link?

<!-- # References -->