---
title: "Replication and Extension of Lucas & Kemp (2015)"
author: "Erin Bennett"
output: 
  html_document:
      toc: true
bibliography: "../../explanations.bib"
---

```{r global_options, include=FALSE}
rm(list=ls())
knitr::opts_chunk$set(echo=F, warning=F, cache=T, message=F, sanitiz =T, fig.width = 5, fig.height = 3)
```

```{r load_settings}
source("~/cocolab/settings/startup.R")
```

```{r load_data}
df = read.csv("../../data/2015-exp4-and-exp5-lkrep.csv") %>%
  select(workerid, story_index, story, variable, rating, version) %>%
  mutate(source = "replication human",
         workerid = factor(as.character(workerid)),
         variable = ifelse(story=="story3a" & variable=="B", "C", as.character(variable)))

frompixel = function(response.pixels, pixel0, pixel1) {
  return(round((response.pixels - pixel0)/(pixel1 - pixel0), 2))
}
lk.orig.data = read.csv("../../data/lkdata.csv") %>%
  mutate(human = mapply(frompixel, humanPixel, pixel0, pixel1),
         model = mapply(frompixel, modelPixel, pixel0, pixel1)) %>%
  select(-humanPixel, -modelPixel, -pixel0, -pixel1) %>%
  gather("source.type", "prob", c(human, model)) %>%
  mutate(source = paste(source,source.type)) %>%
  select(-source.type) %>%
  separate(experiment, c("trash", "story_index"), sep="k") %>%
  select(-trash) %>%
  mutate(story = paste("story", story_index,
                       ifelse(is.na(sub.expt), "",
                              as.character(sub.expt)), sep=""),
         story_index = as.numeric(as.character(story_index))) %>%
  rename(rating = prob) %>%
  mutate(ci.high=rating,
         ci.low=rating) %>%
  select(-sub.expt, -premise, -story_index)
```

```{r}
cf = df %>% filter(version=="counterfactual")
```

## Counterfactuals

A replication of L&K's experiments on mTurk, with `r length(unique(df$workerid))` participants.

```{r}
cf %>%
  group_by(story, variable, source) %>%
  summarise(
    ci.high = ci.high(rating),
    ci.low = ci.low(rating),
    rating = mean(rating)) %>%
  rbind(., lk.orig.data) %>%
  ggplot(., aes(x=variable, y=rating, colour=source, group=source)) +
  geom_point() +
  geom_line() +
  geom_errorbar(aes(x=variable, ymin=ci.low, ymax=ci.high), width=0) +
  facet_wrap(~story, scale="free") +
  ylim(0, 1) +
  theme_black +
  theme(legend.position="right") +
  scale_colour_manual(values=c("steelblue", "white", "green3", "deeppink"))
ggsave("cf.rep.png", width=10, height=8)
```

## Explanations