---
title: "Connection and Strength Parameters"
author: "erindb"
output: html_document
---

```{r}
library(rwebppl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(jsonlite)
```

In this case, no connection could correspond to strength=0.

```{r}
runmodel = function(model) {
  webppl(
    program_file = "connection-and-strength.wppl",
    inference_opts = list(method="enumerate"),
    model_var = model
  )
}
prior = runmodel("prior") %>% mutate(model = "prior")
bcauseA = runmodel("bcauseA") %>% mutate(model = "bcauseA")
acauseB = runmodel("acauseB") %>% mutate(model = "acauseB")
noUtterance = runmodel("noUtterance") %>% mutate(model = "noUtterance")

rbind(prior, bcauseA, acauseB, noUtterance) %>%
  group_by(model, causallyConnected) %>%
  summarise(prob=sum(prob)) %>%
  ggplot(., aes(x=causallyConnected, y=prob, fill=model)) +
  geom_bar(stat="identity", position='dodge')

rbind(prior, bcauseA, acauseB, noUtterance) %>%
  group_by(model, causalStrength) %>%
  summarise(prob=sum(prob)) %>%
  ggplot(., aes(x=causalStrength, y=prob, fill=model)) +
  geom_bar(stat="identity", position='dodge')

rbind(prior, bcauseA, acauseB, noUtterance) %>%
  group_by(model, A) %>%
  summarise(prob=sum(prob)) %>%
  ggplot(., aes(x=A, y=prob, fill=model)) +
  geom_bar(stat="identity", position='dodge')

rbind(prior, bcauseA, acauseB, noUtterance) %>%
  group_by(model, B) %>%
  summarise(prob=sum(prob)) %>%
  ggplot(., aes(x=B, y=prob, fill=model)) +
  geom_bar(stat="identity", position='dodge')

```